### ISSUE TITLE
Check postcard app with Cordova 6

### ISSUE THREAD

**Issue by deadlyfingers** [thaliproject/postcardapp#122]
https://cordova.apache.org/news/2016/01/28/tools-release.html

**Comment by Jambajoo** [comment]
I got story_001 working on cordova 6.0 but Identity Exchange are still having issues. Ref on https://github.com/thaliproject/postcardapp/issues/120

**Comment by deadlyfingers** [comment]
I'm getting build failed error code 65
`fatal error: 'Cordova/CDVViewController.h' file not found`
Related posts:
http://stackoverflow.com/questions/12184767/phonegap-cdvviewcontroller-h-file-not-found-when-archiving-for-ios
- It appears to work if adding cordova platform after installing modules.

Also noticed

```
Installing "org.thaliproject.p2p" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.0.1, failed version requirement: ~3.9.0
Skipping 'org.thaliproject.p2p' for ios
```
- trying "thali": "~2.1.0" package

**Comment by deadlyfingers** [comment]
After trying 2.1.0 package I get iOS build error code 65

```
postcardapp/platforms/ios/PostCardApp/Plugins/io.jxcore.node/CDVJXcore.m:17:9: fatal error: 'Cordova/CDV.h' file not found
#import <Cordova/CDV.h>
```

Removing and adding platform works, but app seems stuck on splashscreen...
**jxcore log:**

```
Feb 16 13:54:29 iPhone-6 PostCardApp[6342] <Warning>: JXcore Cordova plugin initializing
Feb 16 13:54:29 iPhone-6 PostCardApp[6342] <Warning>: JXcore instance initializing
Feb 16 13:54:36 iPhone-6 PostCardApp[6342] <Warning>: Error!: This socket is closed.
    Stack:[{"_fileName":"net.js","_functionName":"Socket.prototype._write","_lineNumber":"582","_columnNumber":"19","_msg":"    at Socket.prototype._write@net.js:582:19"},{"_fileName":"_stream_writable.js","_functionName":"doWrite","_lineNumber":"203","_columnNumber":"3","_msg":"    at doWrite@_stream_writable.js:203:3"},{"_fileName":"_stream_writable.js","_functionName":"writeOrBuffer","_lineNumber":"193","_columnNumber":"5","_msg":"    at writeOrBuffer@_stream_writable.js:193:5"},{"_fileName":"_stream_writable.js","_functionName":"Writable.prototype.write","_lineNumber":"162","_columnNumber":"11","_msg":"    at Writable.prototype.write@_stream_writable.js:162:11"},{"_fileName":"net.js","_functionName":"Socket.prototype.write","_lineNumber":"561","_columnNumber":"10","_msg":"    at Socket.prototype.write@net.js:561:10"},{"_fileName":"console.js","_functionName":"Console.prototype._log","_lineNumber":"52","_columnNumber":"5","_msg":"    at Console.prototype._log@console.js:52:5"},{"_fileName":"console.js","_functionName":"Console.prototype.log","_lineNumber":"60","_columnNumber":"3","_msg":"    at Console.prototype.log@console.js:60:3"},{"_fileName":"/private/var/mobile/Containers/Bundle/Application/F030EA1B-2E3A-49F8-B7D3-945F36752263/PostCardApp.app/www/jxcore/app.js","_functionName":"","_lineNumber":"27","_columnNumber":"1","_msg":"    at @/private/var/mobile/Containers/Bundle/Application/F030EA1B-2E3A-49F8-B7D3-945F36752263/PostCardApp.app/www/jxcore/app.js:27:1"},{"_fileName":"module.js","_functionName":"Module.prototype._compile","_lineNumber":"597","_columnNumber":"10","_msg":"    at Module.prototype._compile@module.js:597:10"}]
Feb 16 13:55:14 iPhone-6 PostCardApp[6346] <Warning>: JXcore Cordova plugin initializing
Feb 16 13:55:14 iPhone-6 PostCardApp[6346] <Warning>: JXcore instance initializing
```

(Closing and reopening app seems to work in this case)

**Comment by deadlyfingers** [comment]
Running `cordova plugins list` shows an old version of JXcore Mobile is being used (0.0.8)
Updating to latest JXcore Mobile (0.1.1) seems to fix issues!

```
jxc install --force
```

**Comment by deadlyfingers** [comment]
It appears Appium can no longer get webview context for testing:

```
 > GET /session/:sessionID/contexts
 > RESPONSE contexts() ["NATIVE_APP"]
webview context: undefined
```
- Appium (1.4.16) 'autoWebview' capability is no longer working following Cordova 6 update and so it is necessary to manually find the webview context. Once the context is set to use the webview then I also need to chain 'setAsyncScriptTimeout' and use 'waitForConditionInBrowser' in first test to make sure app is loaded and ready to test. 
  (Tested on Android device)  

Web driver docs:
https://github.com/admc/wd  
Appium caps:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
